In [42]:
import pandas as pd

In [43]:
df = pd.read_csv("players_data_light-2024_2025.csv")
df

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,Att (GK),Thr,Launch%,AvgLen,Opp,Stp,Stp%,#OPA,#OPA/90,AvgDist
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,25.0,2000.0,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Max Aarons,eng ENG,"DF,MF",Valencia,es La Liga,25.0,2000.0,4,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Rodrigo Abajas,es ESP,DF,Valencia,es La Liga,22.0,2003.0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,James Abankwah,ie IRL,"DF,MF",Udinese,it Serie A,21.0,2004.0,6,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,19.0,2006.0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2849,2850,Edhy Zuliani,it ITA,DF,Toulouse,fr Ligue 1,20.0,2004.0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2850,2851,Szymon Żurkowski,pl POL,MF,Empoli,it Serie A,27.0,1997.0,5,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2851,2852,Martin Ødegaard,no NOR,MF,Arsenal,eng Premier League,26.0,1998.0,30,26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2852,2853,Milan Đurić,ba BIH,FW,Monza,it Serie A,35.0,1990.0,18,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2853,2854,Milan Đurić,ba BIH,FW,Parma,it Serie A,35.0,1990.0,9,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
df = df[["Player","Nation","Pos","Age","PrgC","PrgP","PrgR","G+A","xG+xAG","Min","Squad"]]
df

,Player,Nation,Pos,Age,PrgC,PrgP,PrgR,G+A,xG+xAG,Min,Squad
0,Max Aarons,eng ENG,DF,25.0,1,8,3,0,0.00,86,Bournemouth
1,Max Aarons,eng ENG,"DF,MF",25.0,0,6,10,0,0.02,120,Valencia
2,Rodrigo Abajas,es ESP,DF,22.0,3,2,3,0,0.10,65,Valencia
3,James Abankwah,ie IRL,"DF,MF",21.0,3,4,1,0,0.06,88,Udinese
4,Keyliane Abdallah,fr FRA,FW,19.0,1,0,0,0,0.00,3,Marseille
...,...,...,...,...,...,...,...,...,...,...,...
2849,Edhy Zuliani,it ITA,DF,20.0,0,0,0,0,0.00,9,Toulouse
2850,Szymon Żurkowski,pl POL,MF,27.0,1,1,3,0,0.07,106,Empoli
2851,Martin Ødegaard,no NOR,MF,26.0,92,258,154,11,0.40,2325,Arsenal
2852,Milan Đurić,ba BIH,FW,35.0,2,21,30,5,0.28,1270,Monza
2853,Milan Đurić,ba BIH,FW,35.0,0,7,6,1,0.08,268,Parma

In [45]:
squads = ["Inter","Chelsea","Arsenal","Juventus","Manchester City","Liverpool","Paris S-G",
          "Tottenham","Bayern Munich","Milan",
          "Leverkusen","Juventus",
          "Real Madrid","Manchester Utd","Crystal Palace","Napoli","Valencia",
          "Real Sociedad","Roma","Marseille","Lazio",
          "Dortmund","Mallorca","Sevilla"]
positions = ["FW","MF"]

df = df[(df['Min'] > 1100) & (df['Squad'].isin(squads)) & (df['Pos'].isin(positions))]
df

,Player,Nation,Pos,Age,PrgC,PrgP,PrgR,G+A,xG+xAG,Min,Squad
18,Tammy Abraham,eng ENG,FW,27.0,8,26,69,7,0.70,1183,Milan
43,Lucien Agoume,fr FRA,MF,23.0,29,135,23,4,0.14,2114,Sevilla
238,Bradley Barcola,fr FRA,FW,22.0,137,96,374,24,0.97,2181,Paris S-G
240,Nicolò Barella,it ITA,MF,28.0,63,235,133,9,0.24,2493,Inter
248,Enzo Barrenechea,ar ARG,MF,24.0,21,126,16,3,0.09,2191,Valencia
...,...,...,...,...,...,...,...,...,...,...,...
2791,Granit Xhaka,ch SUI,MF,32.0,42,318,72,9,0.17,2888,Leverkusen
2805,Mattia Zaccagni,it ITA,FW,29.0,91,114,264,14,0.37,2686,Lazio
2815,Andre-Frank Zambo Anguissa,cm CMR,MF,29.0,24,144,119,10,0.22,2852,Napoli
2848,Martín Zubimendi,es ESP,MF,26.0,38,195,43,3,0.11,2962,Real Sociedad
2851,Martin Ødegaard,no NOR,MF,26.0,92,258,154,11,0.40,2325,Arsenal

In [46]:
df.loc[:, 'isBarca'] = 0
df

C:\Users\Admin\AppData\Local\Temp\ipykernel_3660\4279278704.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'isBarca'] = 0

,Player,Nation,Pos,Age,PrgC,PrgP,PrgR,G+A,xG+xAG,Min,Squad,isBarca
18,Tammy Abraham,eng ENG,FW,27.0,8,26,69,7,0.70,1183,Milan,0
43,Lucien Agoume,fr FRA,MF,23.0,29,135,23,4,0.14,2114,Sevilla,0
238,Bradley Barcola,fr FRA,FW,22.0,137,96,374,24,0.97,2181,Paris S-G,0
240,Nicolò Barella,it ITA,MF,28.0,63,235,133,9,0.24,2493,Inter,0
248,Enzo Barrenechea,ar ARG,MF,24.0,21,126,16,3,0.09,2191,Valencia,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2791,Granit Xhaka,ch SUI,MF,32.0,42,318,72,9,0.17,2888,Leverkusen,0
2805,Mattia Zaccagni,it ITA,FW,29.0,91,114,264,14,0.37,2686,Lazio,0
2815,Andre-Frank Zambo Anguissa,cm CMR,MF,29.0,24,144,119,10,0.22,2852,Napoli,0
2848,Martín Zubimendi,es ESP,MF,26.0,38,195,43,3,0.11,2962,Real Sociedad,0
2851,Martin Ødegaard,no NOR,MF,26.0,92,258,154,11,0.40,2325,Arsenal,0

In [47]:
df[df['Player'].str.lower() == 'joshua kimmich']

,Player,Nation,Pos,Age,PrgC,PrgP,PrgR,G+A,xG+xAG,Min,Squad,isBarca
1356,Joshua Kimmich,de GER,MF,30.0,51,362,77,10,0.29,2847,Bayern Munich,0

In [48]:
df.to_csv('new_non_barca.csv', index=False)